name: cartapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  firebase_storage: ^11.3.1
  image_picker: ^1.0.4
  firebase_database: ^10.3.1
  awesome_dialog: ^3.1.0

  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
